name: Nightly Automation

on:
  schedule:
    - cron: '30 18 * * *'   # 12:00 AM IST
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Playwright
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

      - name: Run Tests
        run: mvn clean test

      - name: Upload TestNG Report
        uses: actions/upload-artifact@v4
        with:
          name: TestNG-Report
          path: target/surefire-reports

      - name: Email Test Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Nightly Automation Test Report"
          body: |
            Hi Sanand,

            Nightly Playwright automation has completed.
            Please find the attached report.

            Regards,
            GitHub Actions
          to: ${{ secrets.EMAIL_TO }}
          from: GitHub Automation
          attachments: target/surefire-reports/emailable-report.html
